### ISSUE TITLE
Problem with the less plugin

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal#1292]
Additional info this comes from a normal can-component
- stache works 

my-app is placing it like this

```javascript
    let innerHTML = `
      <div class="container">
        <h1> Main Application </h1>
          <can-import from="can-stache-bindings" />
          <can-import from="~/report/create/report" />
          <components-report></components-report>
      </div>
      <p class="text-center small">Get Suppdort by <a href="#">{{page}}</a></p>
    `

    this.appendChild(stache(innerHTML)(this.viewModel))
```

## ERR

```
Error: Error loading "wartungs-manager@0.1.0#report/create/report.less!steal-less@1.2.0#less" at <unknown>
Error loading "wartungs-manager@0.1.0#report/create/report.less!steal-less@1.2.0#less" from "application/my-app" at http://localhost:8080/application/my-app.js
Error loading "steal-less@1.2.0#less" at http://localhost:8080/node_modules/steal-less/less.js
TypeError: Cannot read property 'dataset' of undefined
	    at addDataAttr (http://localhost:8080/node_modules/less/dist/less.js:807:29)
	    at module.exports (http://localhost:8080/node_modules/less/dist/less.js:21:5)
	    at Object.2../add-default-options (http://localhost:8080/node_modules/less/dist/less.js:74:33)
	    at s (http://localhost:8080/node_modules/less/dist/less.js:14:618)
	    at e (http://localhost:8080/node_modules/less/dist/less.js:14:789)
	    at Function.eval (http://localhost:8080/node_modules/less/dist/less.js:14:807)
	    at execute (http://localhost:8080/node_modules/steal/steal.js:4909:32)
	    at linkDynamicModule (http://localhost:8080/node_modules/steal/steal.js:4077:32)
	    at getModule (http://localhost:8080/node_modules/steal/steal.js:4046:9)
	    at http://localhost:8080/node_modules/steal/steal.js:4081:16
	Evaluating http://localhost:8080/node_modules/steal-less/less-engine.js
	Evaluating http://localhost:8080/node_modules/steal-less/less.js
```

**Comment by matthewp** [comment]
I think you want to use stache.async

**Comment by frank-dspeed** [comment]
@matthewp could you maybe supply me a example how to render stache from string that includes can-import with a define-map?

i think i am missing something and it has something to do with the scope

**Comment by frank-dspeed** [comment]
@matthewp nope the problem is related to require only inside steal with import it works but can be closed as there is at last 1x working method :)
