### ISSUE TITLE
Importing two bundles at the same time fails

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#421]
Probably need to construct working example, but didn't have time for this now.

In my I app I simultaneously import two modules that have shared deps.

`System.import('components/first-parent-component')`

and 

`System.import('components/second-parent-component')`

both depend on `components/shared-component`

`first-parent-component` and `second-parent-component` are built into separate bundles.

In dev mode everyting works fine. In porudction SOMETIMES (most of the time actully) I've got an error:

```
Potentially unhandled rejection [5] TypeError: Error loading "components/shared-component" at http://localhost:2000/assets/components/shared-component.js
Error loading "components/shared-component" from "components/first-parent-module" at http://localhost:2000/assets/components/first-parent-module.js
Error loading "components/shared-component" at http://localhost:2000/assets/components/shared-component.js
Error loading "components/shared-component" from "components/second-parent-component" at http://localhost:2000/assets/components/second-parent-component.js
Cannot read property 'value' of undefined
    at i (http://localhost:2000/bundles/main.js:9:16392)
    at http://localhost:2000/bundles/main.js:9:15155
    at O (http://localhost:2000/bundles/main.js:9:7453)
    at K (http://localhost:2000/bundles/main.js:9:7085)
    at y.7.y.when (http://localhost:2000/bundles/main.js:9:10759)
    at v.7.v.run (http://localhost:2000/bundles/main.js:9:9795)
    at a.3.a._drain (http://localhost:2000/bundles/main.js:9:1746)
    at 3.a.drain (http://localhost:2000/bundles/main.js:9:1400)
    at MutationObserver.b (http://localhost:2000/bundles/main.js:9:3312)(anonymous function) @ main.js:9f @ main.js:9i @ main.js:9
main.js:9 Potentially unhandled rejection [6] TypeError: Error loading "components/shared-component" at http://localhost:2000/assets/components/shared-component.js
Error loading "components/shared-component" from "components/first-parent-module" at http://localhost:2000/assets/components/first-parent-module.js
Error loading "components/shared-component" at http://localhost:2000/assets/components/shared-component.js
Error loading "components/shared-component" from "components/second-parent-component" at http://localhost:2000/assets/components/second-parent-component.js
Cannot read property 'value' of undefined
    at i (http://localhost:2000/bundles/main.js:9:16392)
    at http://localhost:2000/bundles/main.js:9:15155
    at O (http://localhost:2000/bundles/main.js:9:7453)
    at K (http://localhost:2000/bundles/main.js:9:7085)
    at y.7.y.when (http://localhost:2000/bundles/main.js:9:10759)
    at v.7.v.run (http://localhost:2000/bundles/main.js:9:9795)
    at a.3.a._drain (http://localhost:2000/bundles/main.js:9:1746)
    at 3.a.drain (http://localhost:2000/bundles/main.js:9:1400)
    at MutationObserver.b (http://localhost:2000/bundles/main.js:9:3312)(anonymous function) @ main.js:9f @ main.js:9i @ main.js:9
```
And sometimes it loads normally.

This fixes only if I import modules (first and second) not simultaneously.

Any thought what may cause this?

**Comment by matthewp** [comment]
Interesting, isn't there a 3rd bundle that contains the shared dependency between the two?

**Comment by whitecolor** [comment]
Yes there is. Tthe third that `first` and `second` depends on.

**Comment by matthewp** [comment]
Can you post the stacktrace with minification off?

**Comment by matthewp** [comment]
If you're still having this problem, could use a test case. Thanks.
