### ISSUE TITLE
Failed to use with intern js 

### ISSUE THREAD

**Issue by duongphuhiep** [stealjs/steal#452]
I want to use `steal` as a the module loader in [intern](https://theintern.github.io/). Is it possible? How can we do it? I tried but...

`intern.js`
```js
loaders: {
	'host-browser': 'bower_components/steal/steal.js',
	'host-node': 'steal'
}
```
Run ` intern-client config=tests/intern` gives
```
TypeError: Cannot read property 'then' of undefined
  at steal  <node_modules\steal\main.js:197:25>
  at <node_modules\intern\lib\executors\PreExecutor.js:272:5>
  at new Promise  <node_modules\intern\node_modules\dojo\Promise.ts:411:3>
  at PreExecutor._loadExecutorWithLoader  <node_modules\intern\lib\executors\PreExecutor.js:271:11>
  at loadExecutorWithLoader  <node_modules\intern\lib\executors\PreExecutor.js:345:17>
  at <node_modules\intern\node_modules\dojo\Promise.ts:393:15>
  at runCallbacks  <node_modules\intern\node_modules\dojo\Promise.ts:11:11>
  at <node_modules\intern\node_modules\dojo\Promise.ts:317:4>
  at run  <node_modules\intern\node_modules\dojo\Promise.ts:237:7>
  at <node_modules\intern\node_modules\dojo\nextTick.ts:44:3>
```

**Comment by matthewp** [comment]
I'll look into what is going on and report back.

**Comment by matthewp** [comment]
Hey @duongphuhiep, sorry for taking so long to respond. Unfortunately I don't know enough about internjs to help out here. If you could make a sample project and put it on GitHub somewhere I could likely take a look.  I know you might have abandoned steal since this is an old issue, and for that I'm sorry :(
