### ISSUE TITLE
steal .stache dependency load

### ISSUE THREAD

**Issue by mihalycz** [stealjs/steal#552]
Hello!

I have very simple test project. All these files are in the same directory.

**package.json**
```javascript
{
  "name": "canjs-stache",
  "version": "0.0.1",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "system": {
    "npmAlgorithm": "flat",
    "npmIgnore": [
      "devDependencies"
    ],
    "ext": {
      "stache": "can/view/stache/system"
    }
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "can": "latest",
    "steal": "latest",
    "jquery": "2.1.0"
  }
}
```
**hello.stache**

```javascript
Hello World!
```

**main.js**

```javascript
steal("can", "jquery", "hello.stache!", function(can, $, template){
    return can.Component.extend({

    });
});
```
**index.html**

```javascript
<!DOCTYPE html>
<html>
<body>
<div id="app"></div>
<script src="./node_modules/steal/steal.js" data-main="main">
</script>
</body>
</html>
```
**And in the console I receive these errors:**

```javascript
steal.js:2626 GET http://stache:8888/node_modules/can/node_modules/can-simple-dom/package.json 404 (Not Found)

steal.js:2626 GET http://stache:8888/node_modules/can-simple-dom/node_modules/micro-location/package.json 404 (Not Found)

error TypeError: Error loading "hello.stache!can@2.3.9#view/stache/system" at <unknown>(…) TypeError: Error loading "hello.stache!can@2.3.9#view/stache/system" at <unknown>
Error loading "hello.stache!can@2.3.9#view/stache/system" from "main" at http://stache:8888/main.js
Error loading "can@2.3.9#view/stache/system" at http://stache:8888/node_modules/can/view/stache/system.js
$.buildFragment is not a function
    at Object.$.extend.buildFragment (http://stache:8888/node_modules/can/util/jquery/jquery.js:46:12)
    at http://stache:8888/node_modules/can/util/jquery/jquery.js:252:15
    at http://stache:8888/node_modules/can/util/jquery/jquery.js:268:4
    at stealInstantiateResult.execute (http://stache:8888/node_modules/steal/steal.js:5998:32)
    at linkDynamicModule (http://stache:8888/node_modules/steal/steal.js:3547:32)
    at linkDynamicModule (http://stache:8888/node_modules/steal/steal.js:3541:11)
    at linkDynamicModule (http://stache:8888/node_modules/steal/steal.js:3541:11)
    at linkDynamicModule (http://stache:8888/node_modules/steal/steal.js:3541:11)
    at link (http://stache:8888/node_modules/steal/steal.js:3407:11)
    at Object.execute (http://stache:8888/node_modules/steal/steal.js:3726:11)

Potentially unhandled rejection [8] TypeError: Error loading "hello.stache!can@2.3.9#view/stache/system" at <unknown>
Error loading "hello.stache!can@2.3.9#view/stache/system" from "main" at http://stache:8888/main.js
Error loading "can@2.3.9#view/stache/system" at http://stache:8888/node_modules/can/view/stache/system.js
$.buildFragment is not a function
    at Object.$.extend.buildFragment (http://stache:8888/node_modules/can/util/jquery/jquery.js:46:12)
    at http://stache:8888/node_modules/can/util/jquery/jquery.js:252:15
    at http://stache:8888/node_modules/can/util/jquery/jquery.js:268:4
    at stealInstantiateResult.execute (http://stache:8888/node_modules/steal/steal.js:5998:32)
    at linkDynamicModule (http://stache:8888/node_modules/steal/steal.js:3547:32)
    at linkDynamicModule (http://stache:8888/node_modules/steal/steal.js:3541:11)
    at linkDynamicModule (http://stache:8888/node_modules/steal/steal.js:3541:11)
    at linkDynamicModule (http://stache:8888/node_modules/steal/steal.js:3541:11)
    at link (http://stache:8888/node_modules/steal/steal.js:3407:11)
    at Object.execute (http://stache:8888/node_modules/steal/steal.js:3726:11)(anonymous function) @ steal.js:140report @ steal.js:167flush @ steal.js:189
```
Could you please Help me? 
Thank You in Advance!

**Comment by pYr0x** [comment]
which version of canjs, steal and steal-tools do you use?
there was an issue with jquery 2.2

**Comment by mihalycz** [comment]
I'm using the latest versions of canjs (2.3.9), stealjs (0.13.0) and jquery 2.1.0 as you see in my package.json  
"dependencies": {
    "can": "latest",
    "steal": "latest",
    "jquery": "2.1.0"
  }

**Comment by matthewp** [comment]
I would post this in canjs as it will get more attention there. I do think it's a jquery issue, perhaps because can is not using your 2.1.0 version but using it's own 2.2 version.

**Comment by mihalycz** [comment]
But in dependencies section of canjs package.json I see "jquery": ">=1.9.0 <1.12.0 || >=2.1.0 <2.2.0", that is why I installed 2.1.0.

**Comment by matthewp** [comment]
I am looking into the problem, seeing something similar myself.

**Comment by mihalycz** [comment]
resolved by this changes https://github.com/canjs/canjs/pull/2177
