### ISSUE TITLE
Angular2 app fails to load when minified by steal-tools

### ISSUE THREAD

**Issue by wrldtrvllr** [stealjs/steal#681]
Hello,

I've experimented with the Angular2 tutorial (https://github.com/angular/quickstart) and stealjs with npm plugin, which worked out quite well. However, when I tried to build the app with steal-tools, the resulting bundle fails to load with the following error message:

```
TypeError: Error loading "app/main" at http://localhost:3000/app/main.js(…) "TypeError: Error loading "app/main" at http://localhost:3000/app/main.js
Module @angular/core not declared as a dependency.
    at http://localhost:3000/node_modules/steal/steal.js:3575:13
    at http://localhost:3000/node_modules/steal/steal.js:4216:16
    at Function.<anonymous> (http://localhost:3000/dist/bundles/app/main.js:250:1316)
    at define.execute (http://localhost:3000/node_modules/steal/steal.js:4299:32)
    at linkDynamicModule (http://localhost:3000/node_modules/steal/steal.js:3569:32)
    at linkDynamicModule (http://localhost:3000/node_modules/steal/steal.js:3563:11)
    at linkDynamicModule (http://localhost:3000/node_modules/steal/steal.js:3563:11)
    at linkDynamicModule (http://localhost:3000/node_modules/steal/steal.js:3563:11)
    at linkDynamicModule (http://localhost:3000/node_modules/steal/steal.js:3563:11)
    at linkDynamicModule (http://localhost:3000/node_modules/steal/steal.js:3563:11)"
```

This is my package.json:

```
{
  "name": "demo",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "docker-build": "docker build -t ng2-quickstart .",
    "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
    "e2e": "tsc && concurrently \"http-server\" \"protractor protractor.config.js\"",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "build": "steal-tools",
    "postinstall": "typings install",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings",
    "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/upgrade": "2.0.0-rc.1",
    "angular2-in-memory-web-api": "0.0.7",
    "bootstrap": "^3.3.6",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "steal": "^0.16.4",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "canonical-path": "0.0.2",
    "concurrently": "^2.0.0",
    "http-server": "^0.9.0",
    "jasmine-core": "~2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^0.2.3",
    "karma-cli": "^0.1.2",
    "karma-htmlfile-reporter": "^0.2.2",
    "karma-jasmine": "^0.3.8",
    "lite-server": "^2.2.0",
    "lodash": "^4.11.1",
    "protractor": "^3.3.0",
    "rimraf": "^2.5.2",
    "steal-tools": "^0.16.2",
    "tslint": "^3.7.4",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  },
  "main": "app/main",
  "system": {
    "npmAlgorithm": "flat",
    "npmIgnore": [
      "devDependencies"
    ]
  },
  "repository": {}
}
```
It turns out that disabling the minify option makes the bundle work. However, I'd like to use minification as the Angular2 libs are quite big. Any ideas? Or is this maybe a bug in Angular2?

**Comment by justinbmeyer** [comment]
We use uglify for minification. Maybe search there real quick if there are posted issues. Otherwise we will check it out.

**Comment by wrldtrvllr** [comment]
I did some research and it seems that the mangle option breaks it. Is there a way to turn mangling off in steal-tools but still use minification? I didn't find anything in the docs.

**Comment by wrldtrvllr** [comment]
OK, mangling itself is not the problem. However, the uglify-js option "hoist_funs" breaks the code. Using the following configuration provides full minification/mangling while preserving the functionality:

```
uglifyOptions: {
    compress: {
      hoist_funs: false
    }
  }
```

**Comment by justinbmeyer** [comment]
nice work figuring it out!  And thanks for sharing the solution.
