### ISSUE TITLE
Moving to production out dated

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#764]
http://stealjs.com/docs/StealJS.moving-to-prod.html

This should include the `config` setting:

```
stealTools.build({
    config: __dirname+"/package.json!npm"
}, {
  bundleSteal: true
});
```

**Comment by matthewp** [comment]
config shouldn't be required, that's the default, if not it's a bug in steal-tools.

**Comment by justinbmeyer** [comment]
wasn't working w/o it.  Here's what I get:

```
Justins-MacBook-Pro-2:myhub justin$ node build.js 
OPENING: undefined
Potentially unhandled rejection [2] TypeError: Cannot read property 'length' of undefined
    at Loader.loader.normalize (/Users/justin/dev/myhub/node_modules/steal/main.js:274:22)
    at Loader.loader.normalize (/Users/justin/dev/myhub/node_modules/steal/main.js:437:22)
    at Loader.loader.normalize (/Users/justin/dev/myhub/node_modules/steal/main.js:500:36)
    at /Users/justin/dev/myhub/node_modules/steal-tools/lib/graph/make_graph.js:118:48
    at Array.map (native)
    at /Users/justin/dev/myhub/node_modules/steal-tools/lib/graph/make_graph.js:117:37
    at tryCatchReject (/Users/justin/dev/myhub/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/Users/justin/dev/myhub/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/Users/justin/dev/myhub/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
    at ContinuationTask.run (/Users/justin/dev/myhub/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1040:24)
```

**Comment by matthewp** [comment]
Fixed by https://github.com/stealjs/steal-tools/pull/534
