### ISSUE TITLE
build.js unavailable in gh-pages branch

### ISSUE THREAD

**Issue by AryanJ-NYC** [stealjs/steal#881]
On the [Website and Documentation section of the Contributing page](http://stealjs.com/docs/guides.Contributing.html#section_WebsiteandDocumentation), step 4 asks the user to `node build.js`.  There is no `build.js` file to build.

**Comment by matthewp** [comment]
That's weird, not sure why that was there. You only have to do `./node_modules/.bin/documentjs` to generate the docs.

Good catch, I'll update the docs.

**Comment by AryanJ-NYC** [comment]
Oh, I can do it.

Step 5 doesn't work either. Just prints a bunch of `i here`s and ends in an error:

```
Generating docs at docs
WARNING!!
There is no @import tag. did you mean @image ?

WARNING!!
There is no @import tag. did you mean @image ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
There is no @returns tag. did you mean @return ?

WARNING!!
No name for:
 { src: 'steal-tools/lib/bundle/name.js',
  line: 141,
  codeLine: 147,
  body: '\n\t \n',
  description: 'add a prototype method to String\n',
  params: [ { name: 'whatever', description: '' } ],
  _curParam: { name: 'whatever', description: '' },
  returns: '{string}' }
WARNING!!
There is no @method tag. did you mean @author ?

WARNING!!
There is no @method tag. did you mean @author ?

WARNING!!
There is no @method tag. did you mean @author ?

i heree
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
i here
/home/ubuntu/workspace/node_modules/documentjs/node_modules/steal/node_modules/systemjs/node_modules/es6-module-loader/node_modules/traceur/bin/traceur.js:4941
      for (var name = void 0 in this.variableDeclarations) {
               ^^^^^^^^^^^^^

SyntaxError: for-in loop variable declaration may not have an initializer.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/documentjs/node_modules/steal/node_modules/systemjs/node_modules/es6-module-loader/node_modules/traceur/src/node/traceur.js:24:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/documentjs/node_modules/steal/node_modules/systemjs/node_modules/es6-module-loader/node_modules/traceur/src/node/api.js:23:15)
```

**Comment by matthewp** [comment]
Let me try a fresh copy.

**Comment by matthewp** [comment]
Yeah, I see the same thing. Looking into what it might be. The `I here` is hilarious.
